<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>tripleo.elijah</groupId>
	<artifactId>congenial-robot</artifactId>
	<packaging>pom</packaging>
	<version>congenial.2023-12</version>

	<name>eljc-almost-congenial-robot</name>
	<url>http://git.sr.ht/~tripleo/el-almost</url>

	<properties>
		<project.build.outputTimestamp>1</project.build.outputTimestamp>
		<downloadSources>true</downloadSources>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

		<java.version>17</java.version>
		<maven.compiler.source>17</maven.compiler.source>
		<maven.compiler.target>17</maven.compiler.target>

		<jacoco.version>0.8.9</jacoco.version>
		<guava.version>32.0.0-jre</guava.version>

		<buffers.version>0.0.3</buffers.version>
		<range.version>0.0.3b</range.version>

		<maven-compiler-plugin.version>3.8.1</maven-compiler-plugin.version>
		<kotlin.version>2.1.10</kotlin.version>
	</properties>

	<modules>
		<module>elijah-congenial-core</module>
		<module>elijah-congenial-core.test</module>
	</modules>

	<dependencies>
<!--
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<scope>provided</scope>
		</dependency>
-->
		<dependency>
			<groupId>javax.annotation</groupId>
			<artifactId>javax.annotation-api</artifactId>
		</dependency>
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-lang3</artifactId>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-simple</artifactId>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
		</dependency>
		<dependency>
			<groupId>org.mockito</groupId>
			<artifactId>mockito-core</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>com.gitlab.tripleo1</groupId>
			<artifactId>buffers</artifactId>
		</dependency>
		<dependency>
			<groupId>com.gitlab.Tripleo</groupId>
			<artifactId>range</artifactId>
		</dependency>
	</dependencies>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.projectlombok</groupId>
				<artifactId>lombok</artifactId>
				<version>1.18.42</version>
			</dependency>
			<dependency>
				<groupId>javax.annotation</groupId>
				<artifactId>javax.annotation-api</artifactId>
				<version>1.3.2</version>
			</dependency>
			<dependency>
				<groupId>org.apache.commons</groupId>
				<artifactId>commons-lang3</artifactId>
				<version>3.20.0</version>
			</dependency>
			<dependency>
				<groupId>org.slf4j</groupId>
				<artifactId>slf4j-simple</artifactId>
				<version>2.1.0-alpha1</version>
			</dependency>
			<dependency>
				<groupId>org.slf4j</groupId>
				<artifactId>slf4j-api</artifactId>
				<version>2.1.0-alpha1</version>
			</dependency>
			<dependency>
				<groupId>org.mockito</groupId>
				<artifactId>mockito-core</artifactId>
				<version>5.20.0</version>
			</dependency>
			<dependency>
				<groupId>com.gitlab.tripleo1</groupId>
				<artifactId>buffers</artifactId>
				<version>3038ff102c</version>
			</dependency>
			<dependency>
				<groupId>com.gitlab.Tripleo</groupId>
				<artifactId>range</artifactId>
				<version>0.0.3b</version>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<repositories>
		<repository>
			<id>jitpack.io</id>
			<url>https://jitpack.io</url>
		</repository>
	</repositories>

	<build>
		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>org.owasp</groupId>
					<artifactId>dependency-check-maven</artifactId>
					<version>8.2.1</version>
				</plugin>
				<plugin>
					<groupId>org.codehaus.mojo</groupId>
					<artifactId>versions-maven-plugin</artifactId>
					<version>2.15.0</version>
				</plugin>
			</plugins>
		</pluginManagement>
		<plugins>
			<plugin>
				<groupId>org.owasp</groupId>
				<artifactId>dependency-check-maven</artifactId>
				<configuration>
					<skipProvidedScope>true</skipProvidedScope>
					<cveValidForHours>8</cveValidForHours>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>versions-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

	<!--
	<reporting>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-checkstyle-plugin</artifactId>
				<version>3.3.0</version>
				<configuration>
					<configLocation>checkstyle.xml</configLocation>
				</configuration>
				<reportSets>
					<reportSet>
						<reports>
							<report>checkstyle</report>
						</reports>
					</reportSet>
				</reportSets>
			</plugin>
		</plugins>
	</reporting>
	-->
</project>
